FROM ubuntu:20.04
LABEL maintainer "jjaegii <hn06038@gmail.com>"

RUN apt-get update && apt-get install python3 python3-pip -y
ENV IMAGE_DIR images
WORKDIR /app
COPY requirements.txt .
# RUN pip3 install -r requirements.txt
RUN pip install flask ultralytics

COPY detect.py .
COPY templates/* templates/
COPY test_img.jpg .

COPY model/yolov8n.pt model/.
ENTRYPOINT [ "python3" ]
CMD ["detect.py"]