name: CI Workflow

on: [push, pull_request]

jobs:
  test-build-deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install ultralytics flask

    - name: Run tests
      run: |
        python -m unittest draw_test.py
        python -m unittest detect_test.py

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build -t jjaegii/draw:latest -f Dockerfile.draw .
        docker build -t jjaegii/detect:latest -f Dockerfile.detect .
        docker push jjaegii/draw:latest 
        docker push jjaegii/detect:latest

    - name: Code style check (PEP8)
      uses: ricardochaves/python-lint@v1.1.0
      with:
        python-root-list: '.'