name: CI Workflow

on: [push, pull_request]

jobs:
  test-build-deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python draw_test.py
        python detect_test.py

    - name: Build and push Docker images
      run: |
        docker build -t jjaegii/draw:latest -f Dockerfile.draw .
        docker build -t jjaegii/detect:latest -f Dockerfile.detect .
        echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        docker push jjaegii/draw:latest 
        docker push jjaegii/detect:latest
        docker build -t detect:latest -f Dockerfile.detect .

    - name: Code style check (PEP8)
      uses: ricardochaves/python-lint@v1.1.0
      with:
        python-root-list: '.'

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
